/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:1ac4b299-6bba-45f7-b2c5-9ac1f52da127",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_hn1RxzJne",
    "aws_user_pools_web_client_id": "4lr60nffl66ii74rgobtrk5fd5",
    "oauth": {},
    "aws_user_files_s3_bucket": "univa-frontddea0ec3db934773902f35abcf4195d2testtwo-testtwo",
    "aws_user_files_s3_bucket_region": "ap-northeast-2",
    "aws_appsync_graphqlEndpoint": "https://ly5tyt6iivbk7l2d5jcs4ocp4e.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-xph52hd375eo7ggi4qo36cnfxu"
};


export default awsmobile;
